<?php

return [
    ['GET', '/', 'Admin\Controllers\HomeController:index'],
    ['GET', '/logout', 'Admin\Controllers\HomeController:logout'],

    ['GET', '/error-403', 'Admin\Controllers\ErrorController:error403'],
    ['GET', '/error-banned', 'Admin\Controllers\ErrorController:errorBanned'],

    ['GET', '/login', 'Admin\Controllers\PublicController:login'],
    ['POST', '/login', 'Admin\Controllers\PublicController:login'],

    ['GET', '/language/{langId:[_a-z]+}', 'Admin\Controllers\PublicController:language'],
    ['GET', '/login-logs', 'Admin\Controllers\ActionController:loginLogs'],

    ['GET', '/attachment/{name:\w+\.\w+}', 'Admin\Controllers\HomeController:attachment'],

    ['GET', '/users/', 'Admin\Controllers\UserController:index'],
    ['GET', '/user/edit/[{id:\d+}]', 'Admin\Controllers\UserController:edit'],
    ['GET', '/user/password/{id:\d+}', 'Admin\Controllers\UserController:password'],
    ['POST', '/user/save-password', 'Admin\Controllers\UserController:savePassword'],
    ['GET', '/user/view/{id:\d+}', 'Admin\Controllers\UserController:view'],
    ['POST', '/user/save', 'Admin\Controllers\UserController:save'],
    ['POST', '/user/delete', 'Admin\Controllers\UserController:delete'],
    ['GET', '/user/user', 'Admin\Controllers\UserController:user'],
    ['POST', '/users/authorize', 'Admin\Controllers\UserController:authorize'],
    ['POST', '/user/reviewers/{type}', 'Admin\Controllers\UserController:reviewers'],
    ['POST', '/user/editors/{type}', 'Admin\Controllers\UserController:editors'],

    ['POST', '/crop/upload', 'Admin\Controllers\FileController:cropUpload'],
    ['POST', '/upload/{type:\w+}', 'Admin\Controllers\FileController:upload'],
    ['POST', '/froala/upload/{type:\w+}', 'Admin\Controllers\FileController:froalaUpload'],

    ['GET', '/file/images/', 'Admin\Controllers\FileController:images'],
    ['GET', '/file/videos/', 'Admin\Controllers\FileController:videos'],
    ['GET', '/file/files/', 'Admin\Controllers\FileController:files'],
    ['POST', '/file/delete', 'Admin\Controllers\FileController:delete'],
    ['POST', '/file/batch/delete', 'Admin\Controllers\FileController:batchDelete'],
    ['GET', '/modal/images/', 'Admin\Controllers\FileController:ajaxImages'],
    ['GET', '/modal/videos/', 'Admin\Controllers\FileController:ajaxVideos'],
    ['GET', '/modal/files/', 'Admin\Controllers\FileController:ajaxFiles'],
    ['GET', '/froala/images/', 'Admin\Controllers\FileController:froalaImages'],

    ['GET', '/models/', 'Admin\Controllers\ModelController:index'],
    ['GET', '/model/edit/[{id:\d+}]', 'Admin\Controllers\ModelController:edit'],
    ['POST', '/model/save', 'Admin\Controllers\ModelController:save'],
    ['POST', '/model/delete', 'Admin\Controllers\ModelController:delete'],
    ['POST', '/model/parents', 'Admin\Controllers\ModelController:parents'],

    ['GET', '/fields/{model_id:\d+}', 'Admin\Controllers\FieldController:index'],
    ['GET', '/field/edit/{model_id:\d+}/[{id:\d+}]', 'Admin\Controllers\FieldController:edit'],
    ['POST', '/field/save', 'Admin\Controllers\FieldController:save'],
    ['POST', '/field/delete', 'Admin\Controllers\FieldController:delete'],
    ['POST', '/field/sort', 'Admin\Controllers\FieldController:sort'],
    ['GET', '/field/modify/{model_id:\d+}/[{id:\d+}]', 'Admin\Controllers\FieldController:modify'],
    ['GET', '/field/modify2/{model_id:\d+}/[{id:\d+}]', 'Admin\Controllers\FieldController:modify2'],
    ['POST', '/field/keep', 'Admin\Controllers\FieldController:keep'],

    ['GET', '/pages/', 'Admin\Controllers\PageController:index'],
    ['GET', '/page/edit/[{id:\d+}]', 'Admin\Controllers\PageController:edit'],
    ['GET', '/page/view/[{id:\d+}]', 'Admin\Controllers\PageController:view'],
    ['POST', '/page/save', 'Admin\Controllers\PageController:save'],
    ['POST', '/page/copy/{id:\d+}', 'Admin\Controllers\PageController:copy'],
    ['POST', '/page/delete', 'Admin\Controllers\PageController:delete'],
    ['POST', '/page/sort', 'Admin\Controllers\PageController:sort'],
    ['POST', '/page/title/update/{id:\d+}', 'Admin\Controllers\PageController:title'],
    ['POST', '/page/shortcut/update/{id:\d+}', 'Admin\Controllers\PageController:shortcut'],
    ['POST', '/page/slug/update/{id:\d+}', 'Admin\Controllers\PageController:slug'],
    ['POST', '/page/hidden/update/{id:\d+}', 'Admin\Controllers\PageController:hidden'],
    ['POST', '/page/review/update/{id:\d+}', 'Admin\Controllers\PageController:review'],
    ['POST', '/page/ban-delete/{id:\d+}', 'Admin\Controllers\PageController:banDelete'],
    ['POST', '/page/ban-children/{id:\d+}', 'Admin\Controllers\PageController:banChildren'],
    ['GET', '/page/preview/{id:\d+}', 'Admin\Controllers\PageController:preview'],
    ['GET', '/page/histories/{id:\d+}', 'Admin\Controllers\PageController:histories'],
    ['GET', '/page/find/{id:\d+}', 'Admin\Controllers\PageController:find'],
    ['POST', '/page/grant/agencies', 'Admin\Controllers\PageController:grantAgencies'],
    ['POST', '/page/grant/reviewers', 'Admin\Controllers\PageController:grantReviewers'],
    ['POST', '/page/grant/editors', 'Admin\Controllers\PageController:grantEditors'],

    ['GET', '/catalogs/{cType:[-\w]+}/{type:[-\w]+}', 'Admin\Controllers\CatalogController:index'],
    ['GET', '/catalog/edit/{cType:[-\w]+}/{type:[-\w]+}/[{id:\d+}]', 'Admin\Controllers\CatalogController:edit'],
    ['POST', '/catalog/save/{cType:[-\w]+}/{type:[-\w]+}', 'Admin\Controllers\CatalogController:save'],
    ['POST', '/catalog/delete', 'Admin\Controllers\CatalogController:delete'],
    ['POST', '/catalog/sort', 'Admin\Controllers\CatalogController:sort'],
    ['POST', '/catalog/ban-delete/{id:\d+}', 'Admin\Controllers\CatalogController:banDelete'],
    ['POST', '/catalog/ban-children/{id:\d+}', 'Admin\Controllers\CatalogController:banChildren'],
    ['POST', '/catalog/slug/update/{id:\d+}', 'Admin\Controllers\CatalogController:slug'],

    ['GET', '/catalogs/', 'Admin\Controllers\CatalogController:index'],
    ['GET', '/catalog/edit/[{id:\d+}]', 'Admin\Controllers\CatalogController:edit'],
    ['POST', '/catalog/save/', 'Admin\Controllers\CatalogController:save'],

    ['GET', '/posts/{type:[-\w]+}[/{cat:\d+}]', 'Admin\Controllers\PostController:index'],
    ['GET', '/post/edit/{type:[-\w]+}/[{id:\d+}]', 'Admin\Controllers\PostController:edit'],
    ['POST', '/post/sorts', 'Admin\Controllers\PostController:sorts'],
    ['POST', '/post/save/[{type:[-\w]+}]', 'Admin\Controllers\PostController:save'],
    ['POST', '/post/copy/{type:[-\w]+}/{id:\d+}', 'Admin\Controllers\PostController:copy'],
    ['POST', '/post/delete/{type:[-\w]+}', 'Admin\Controllers\PostController:delete'],
    ['POST', '/post/batch/copy/{type:[-\w]+}', 'Admin\Controllers\PostController:batchCopy'],
    ['POST', '/post/batch/delete/{type:[-\w]+}', 'Admin\Controllers\PostController:batchDelete'],
    ['POST', '/post/export/{type:[-\w]+}', 'Admin\Controllers\PostController:export'],
    ['GET', '/post/import/{type:[-\w]+}', 'Admin\Controllers\PostController:import'],

    ['POST', '/post/title/update/{id:\d+}', 'Admin\Controllers\PostController:title'],
    ['POST', '/post/slug/update/{id:\d+}', 'Admin\Controllers\PostController:slug'],
    ['POST', '/post/sort/update/{id:\d+}', 'Admin\Controllers\PostController:sort'],
    ['POST', '/post/hidden/update/{id:\d+}', 'Admin\Controllers\PostController:hidden'],
    ['POST', '/post/review/update/{id:\d+}', 'Admin\Controllers\PostController:review'],
    ['GET', '/post/preview/{id:\d+}', 'Admin\Controllers\PostController:preview'],
    ['GET', '/post/histories/{id:\d+}', 'Admin\Controllers\PostController:histories'],

    ['GET', '/settings/{file}', 'Admin\Controllers\SettingController:edit'],
    ['POST', '/settings/save/{file}', 'Admin\Controllers\SettingController:save'],
    ['POST', '/settings/email-test', 'Admin\Controllers\SettingController:emailTest'],

    ['GET', '/menus/', 'Admin\Controllers\MenuController:index'],
    ['GET', '/menu/edit/[{id:\d+}]', 'Admin\Controllers\MenuController:edit'],
    ['POST', '/menu/save', 'Admin\Controllers\MenuController:save'],
    ['POST', '/menu/delete', 'Admin\Controllers\MenuController:delete'],

    ['GET', '/navs/{menu_id:\d+}', 'Admin\Controllers\NavController:index'],
    ['GET', '/nav/edit/{menu_id:\d+}/[{id:\d+}]', 'Admin\Controllers\NavController:edit'],
    ['POST', '/nav/save', 'Admin\Controllers\NavController:save'],
    ['POST', '/nav/hidden/update/{id:\d+}', 'Admin\Controllers\NavController:hidden'],
    ['POST', '/nav/delete', 'Admin\Controllers\NavController:delete'],
    ['GET', '/nav/data/{type: \w+}', 'Admin\Controllers\NavController:data'],
    ['POST', '/nav/sort', 'Admin\Controllers\NavController:sort'],
    ['GET', '/nav/target/{type}/{id}', 'Admin\Controllers\NavController:target'],

    ['GET', '/actions/', 'Admin\Controllers\ActionController:index'],

    ['GET', '/translations', 'Admin\Controllers\TranslationController:index'],
    ['POST', '/translation/save', 'Admin\Controllers\TranslationController:save'],
    ['POST', '/translation/delete', 'Admin\Controllers\TranslationController:delete'],
    ['GET', '/translation/{id:\d+}', 'Admin\Controllers\TranslationController:find'],
    ['POST', '/translations/export', 'Admin\Controllers\TranslationController:export'],
    ['POST', '/translations/import', 'Admin\Controllers\TranslationController:import'],

    ['GET', '/members/{group}', 'Admin\Controllers\MemberController:index'],
    ['GET', '/member/edit/[{id:\d+}]', 'Admin\Controllers\MemberController:edit'],
    ['GET', '/member/password/{id:\d+}', 'Admin\Controllers\MemberController:password'],
    ['POST', '/member/save-password', 'Admin\Controllers\MemberController:savePassword'],
    ['GET', '/member/view/{id:\d+}', 'Admin\Controllers\MemberController:view'],
    ['POST', '/member/save', 'Admin\Controllers\MemberController:save'],
    ['POST', '/member/password', 'Admin\Controllers\MemberController:password'],
    ['GET', '/member/detail/{id:\d+}', 'Admin\Controllers\MemberController:detail'],
    ['POST', '/member/export', 'Admin\Controllers\MemberController:export'],
    ['POST', '/member/delete', 'Admin\Controllers\MemberController:delete'],

    ['GET', '/member-groups/', 'Admin\Controllers\MemberGroupController:index'],
    ['GET', '/member-group/edit/[{id:\d+}]', 'Admin\Controllers\MemberGroupController:edit'],
    ['POST', '/member-group/save', 'Admin\Controllers\MemberGroupController:save'],
    ['POST', '/member-group/delete', 'Admin\Controllers\MemberGroupController:delete'],

    ['GET', '/forms/', 'Admin\Controllers\FormController:index'],
    ['GET', '/form/edit/[{id:\d+}]', 'Admin\Controllers\FormController:edit'],
    ['POST', '/form/save', 'Admin\Controllers\FormController:save'],
    ['POST', '/form/delete', 'Admin\Controllers\FormController:delete'],
    ['POST', '/form/batch-delete', 'Admin\Controllers\FormController:batchDelete'],
    ['GET', '/form/html/{id:\d+}', 'Admin\Controllers\FormController:html'],

    ['GET', '/form-fields/{id:\d+}', 'Admin\Controllers\FormFieldController:index'],
    ['POST', '/form-fields/sort', 'Admin\Controllers\FormFieldController:sort'],
    ['GET', '/form-field/edit/{fid:\d+}/[{id:\d+}]', 'Admin\Controllers\FormFieldController:edit'],
    ['POST', '/form-field/save', 'Admin\Controllers\FormFieldController:save'],
    ['POST', '/form-field/delete', 'Admin\Controllers\FormFieldController:delete'],

    ['GET', '/submissions/{fid:\d+}', 'Admin\Controllers\SubmissionController:index'],
    ['GET', '/submission/detail/{id:\d+}', 'Admin\Controllers\SubmissionController:detail'],
    ['POST', '/submission/delete', 'Admin\Controllers\SubmissionController:delete'],
    ['POST', '/submission/batch-delete/{fid:\d+}', 'Admin\Controllers\SubmissionController:batchDelete'],
    ['POST', '/submission/export/{fid:\w+}', 'Admin\Controllers\SubmissionController:export'],
    ['POST', '/submission/review/update/{id:\d+}', 'Admin\Controllers\SubmissionController:review'],
    ['POST', '/submission/replied/{id:\d+}', 'Admin\Controllers\SubmissionController:replied'],

    ['GET', '/templates', 'Admin\Controllers\TemplateController:index'],
    ['GET', '/templates/{name:[-\w]+}', 'Admin\Controllers\TemplateController:find'],
    ['POST', '/profile/{type:[-\w]+}', 'Admin\Controllers\ProfileController:load'],

    ['GET', '/extend/page/{id:\d+}', 'Admin\Controllers\ExtendController:page'],
    ['GET', '/extend/catalog/{subtype:[-\w]+}/{group:[-\w]+}[/{id:\d+}]', 'Admin\Controllers\ExtendController:catalog'],
    ['GET', '/extend/category/{subtype:[-\w]+}[/{id:\d+}]', 'Admin\Controllers\ExtendController:category'],
    ['GET', '/extend/post/{subtype:[-\w]+}/{id}', 'Admin\Controllers\ExtendController:post'],
    ['GET', '/extend/activity', 'Admin\Controllers\ExtendController:activity'],
    ['GET', '/extend/list-item/{subtype:[-\w]+}', 'Admin\Controllers\ExtendController:listItem'],
    ['GET', '/extend/setting/{id:\d+}', 'Admin\Controllers\ExtendController:setting'],
    ['GET', '/extend/list/{id}', 'Admin\Controllers\ExtendController:list'],

    ['GET', '/accesses', 'Admin\Controller\AccessController:index'],
    ['GET', '/accesses/add', 'Admin\Controller\AccessController:add'],
    ['POST', '/accesses/create', 'Admin\Controller\AccessController:create'],
    ['GET', '/accesses/edit/{id:\d+}', 'Admin\Controller\AccessController:edit'],
    ['POST', '/accesses/update', 'Admin\Controller\AccessController:update'],
    ['POST', '/accesses/delete', 'Admin\Controller\AccessController:delete'],
    ['POST', '/accesses/sorts', 'Admin\Controller\AccessController:sorts'],

    ['GET', '/roles', 'Admin\Controller\RoleController:index'],
    ['GET', '/roles/add', 'Admin\Controller\RoleController:add'],
    ['POST', '/roles/create', 'Admin\Controller\RoleController:create'],
    ['GET', '/roles/edit/{id:\d+}', 'Admin\Controller\RoleController:edit'],
    ['POST', '/roles/update', 'Admin\Controller\RoleController:update'],
    ['POST', '/roles/delete', 'Admin\Controller\RoleController:delete'],

    ['GET', '/permissions/edit/{role_id:\d+}', 'Admin\Controller\PermissionController:edit'],
    ['POST', '/permissions/save', 'Admin\Controller\PermissionController:save'],

    ['GET', '/system-setting', 'Admin\Controllers\SystemSettingController:edit'],
    ['POST', '/system-setting/save', 'Admin\Controllers\SystemSettingController:save'],

    ['GET', '/system/types', 'Admin\Controller\ArticleTypeController:index'],
    ['GET', '/system/types/add', 'Admin\Controller\ArticleTypeController:add'],
    ['POST', '/system/types/create', 'Admin\Controller\ArticleTypeController:create'],
    ['GET', '/system/types/edit/{id:\d+}', 'Admin\Controller\ArticleTypeController:edit'],
    ['POST', '/system/types/update', 'Admin\Controller\ArticleTypeController:update'],
    ['POST', '/system/types/delete', 'Admin\Controller\ArticleTypeController:delete'],

    ['GET', '/subscribers', 'Admin\Controllers\SubscriberController:index'],
    ['POST', '/subscribers/export', 'Admin\Controllers\SubscriberController:export'],
    ['POST', '/subscribers/delete', 'Admin\Controllers\SubscriberController:delete'],
    ['POST', '/subscribers/batch-delete', 'Admin\Controllers\SubscriberController:batchDelete'],

    ['GET', '/list-items/{lid}', 'Admin\Controllers\ListItemController:index'],
    ['GET', '/list-items/edit/{fid:\d+}[/{iid}]', 'Admin\Controllers\ListItemController:edit'],
    ['POST', '/list-items/save', 'Admin\Controllers\ListItemController:save'],
    ['POST', '/list-items/delete/{id}', 'Admin\Controllers\ListItemController:delete'],
    ['POST', '/list-items/sort', 'Admin\Controllers\ListItemController:sort'],
];
